#!/usr/bin/env python3
"""
check-existing-agents-md.py - Check if AGENTS.md exists and determine if it was generated by this tool

Purpose: Detect existing AGENTS.md files and determine if they were generated by this tool
         or manually created, to prevent accidental overwrites

Usage:
    python check-existing-agents-md.py [TARGET_FOLDER_PATH]

Exit codes:
    0 = No AGENTS.md exists (safe to proceed)
    1 = AGENTS.md exists and was generated by this tool (can backup and overwrite)
    2 = AGENTS.md exists and was manually created (should not overwrite)
    3 = Error (folder not found, cannot read file)
"""

import os
import sys
import re
from pathlib import Path
from datetime import datetime


def is_generated_by_tool(agents_md_path: Path) -> bool:
    """Check if AGENTS.md was generated by this tool."""
    try:
        with open(agents_md_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check for tool signature in frontmatter
        # Look for patterns that indicate tool generation:
        # 1. "Generated by agents-md-generator" or similar
        # 2. Specific frontmatter structure
        # 3. "Progressive Context Loading Protocol" section (tool-specific)
        
        # Check frontmatter for tool signature
        if content.startswith('---'):
            parts = content.split('---', 2)
            if len(parts) >= 2:
                frontmatter = parts[1]
                # Look for tool-specific markers
                if 'agents-md-generator' in frontmatter.lower():
                    return True
                if 'progressive context loading' in frontmatter.lower():
                    return True
        
        # Check for tool-specific sections
        if '## 🎯 CONTEXT: Progressive Context Loading Protocol' in content:
            return True
        if 'Level 1: Front Matter' in content and 'Level 2: AGENTS.md Content' in content:
            return True
        
        # Check for generated timestamp pattern
        if re.search(r'Generated.*\d{4}-\d{2}-\d{2}', content):
            return True
        
        return False
    
    except Exception as e:
        print(f"Error reading AGENTS.md: {e}", file=sys.stderr)
        return False


def check_existing_agents_md(folder_path: str) -> dict:
    """Check if AGENTS.md exists in target folder."""
    folder = Path(folder_path)
    
    if not folder.exists():
        return {
            'exists': False,
            'error': f"Folder not found: {folder_path}",
            'status': 'error'
        }
    
    if not folder.is_dir():
        return {
            'exists': False,
            'error': f"Path is not a directory: {folder_path}",
            'status': 'error'
        }
    
    agents_md_path = folder / 'AGENTS.md'
    
    if not agents_md_path.exists():
        return {
            'exists': False,
            'status': 'not_exists',
            'message': 'AGENTS.md does not exist - safe to proceed'
        }
    
    # File exists - check if generated by tool
    is_tool_generated = is_generated_by_tool(agents_md_path)
    
    if is_tool_generated:
        return {
            'exists': True,
            'status': 'tool_generated',
            'path': str(agents_md_path),
            'message': 'AGENTS.md exists and was generated by this tool - can backup and overwrite',
            'can_overwrite': True
        }
    else:
        return {
            'exists': True,
            'status': 'manually_created',
            'path': str(agents_md_path),
            'message': 'AGENTS.md exists and appears to be manually created - should NOT overwrite',
            'can_overwrite': False
        }


def create_backup(agents_md_path: Path) -> str:
    """Create backup of existing AGENTS.md file."""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_path = agents_md_path.parent / f'AGENTS.md.backup.{timestamp}'
    
    try:
        import shutil
        shutil.copy2(agents_md_path, backup_path)
        return str(backup_path)
    except Exception as e:
        raise Exception(f"Failed to create backup: {e}")


def main():
    """Main execution function."""
    if len(sys.argv) < 2:
        print("Error: Target folder path required", file=sys.stderr)
        print("Usage: python check-existing-agents-md.py [TARGET_FOLDER_PATH]", file=sys.stderr)
        sys.exit(3)
    
    folder_path = sys.argv[1]
    
    result = check_existing_agents_md(folder_path)
    
    # Print result as JSON for programmatic use
    import json
    print(json.dumps(result, indent=2))
    
    # Exit with appropriate code
    if result.get('status') == 'error':
        sys.exit(3)
    elif result.get('status') == 'not_exists':
        sys.exit(0)
    elif result.get('status') == 'tool_generated':
        sys.exit(1)
    elif result.get('status') == 'manually_created':
        sys.exit(2)
    else:
        sys.exit(3)


if __name__ == '__main__':
    main()

